---
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  name: validating-webhook-configuration
webhooks:
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /validate-setec-zero-day-ai-v1alpha1-sandbox
  failurePolicy: Fail
  name: vsandbox.setec.zero-day.ai
  rules:
  - apiGroups:
    - setec.zero-day.ai
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - sandboxes
  sideEffects: None
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /validate-setec-zero-day-ai-v1alpha1-snapshot
  failurePolicy: Fail
  name: vsnapshot.setec.zero-day.ai
  rules:
  - apiGroups:
    - setec.zero-day.ai
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - snapshots
  sideEffects: None
